FROM nginx
WORKDIR /home/
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./server.c .
COPY ./run.sh .
RUN chmod +x run.sh \
    && apt-get update \
    && apt-get install -y gcc spawn-fcgi libfcgi-dev
ENTRYPOINT ["./run.sh"]
